// Portfolio content. Replace placeholder media and extend case studies here.
const projects = [
 {id:'gamma',title:'GammaDesk',category:'product',kind:'Research → Product',year:'2026',image:'gamma-real.webp',featured:true,description:'Making the market easier to read.',body:'A bilingual dashboard that brings macro conditions, options positioning, and market breadth into one research workflow.',role:'Research framework · Product design · Development',details:['Combined macro indicators and market structure into a weighted risk framework.','Designed daily reviews, input coverage indicators, and AI-generated research summaries.','Built with AI coding agents and financial data APIs, then deployed with GitHub and Vercel.'],stack:'MarketData.app · Alpaca · Tiingo · OpenAI · Vercel',link:'https://trading-gamma-desk.vercel.app',linkLabel:'Open live product',note:'Screen capture from the working GammaDesk application.'},
 {id:'invisible',title:'Invisible!',category:'space',kind:'Worldbuilding · Game environment',year:'2019–2021',image:'invisible.webp',featured:true,description:'An imagined world, made tangible.',body:'A game-environment project exploring constructed landscapes and atmospheric digital worlds.',role:'Environment design · Visual development',gallery:['invisible.webp','invisible-city.webp'],details:['Selected images from the original digital portfolio.','The full project story, collaborators, and production details will be added in the next edition.']},
 {id:'signal',title:'Signal-Lab',category:'product',kind:'Research · Rule-based tools',year:'2026',image:'signal-thumbnail.png',video:'signal-demo.mp4',description:'From observation to repeatable rules.',body:'A TradingView indicator translating price-action research into entry alerts, staged exits, and ATR-based risk controls.',role:'Research · Rule design · Indicator development',details:['Studied consolidation, volume, trend, and entry confirmation across historical signals.','Developed staged exits and ATR-based risk controls.','Refined a focused alert using comparative signal cohorts.'],stack:'TradingView · Pine Script · Historical market data',note:'TradingView replay showing the indicator’s rule-based signals.'},
 {id:'gravity',title:'Gravity Infill',category:'space',kind:'Architecture · Simulation',year:'2019–2021',image:'gravity.webp',description:'Architecture beyond the static object.',body:'An architectural simulation exploring speculative interventions within an urban environment.',role:'Spatial design · Digital simulation',gallery:['gravity.webp','gravity-city.webp'],details:['Selected imagery from the original portfolio. Detailed process and project credits to follow.']},
 {id:'spectrum',title:'Spectrum',category:'experiment',kind:'Augmented reality · Mobile',year:'2019–2021',image:'spectrum.webp',description:'A digital layer over the everyday.',body:'An augmented-reality mobile project that brings playful digital forms into a physical setting.',role:'AR experience · Interaction · Visual design',gallery:['spectrum.webp'],link:'https://vimeo.com/489187386',linkLabel:'Watch project film',details:['Selected imagery from the original portfolio. The full interaction walkthrough and credits will be added.']},
 {id:'hollywood',title:'Hollywood Hongkong',category:'space',kind:'Virtual reality · Scene design',year:'2019–2021',image:'hollywood.webp',description:'A cinematic place to step inside.',body:'A VR movie-scene project exploring atmosphere, light, and the experience of a digital environment.',role:'VR scene · Environment design',gallery:['hollywood.webp'],details:['Selected imagery from the original portfolio. Project context and production details to follow.']},
 {id:'earth',title:'Earth Odyssey',category:'product',kind:'Web application · Travel',year:'2023',image:'earth.webp',description:'Travel plans, brought together.',body:'An all-in-one itinerary application for organizing personal travel information.',role:'Full-stack development · Interface design',link:'https://github.com/hreisis/earthOdessay',linkLabel:'View source code',details:['A self-directed web application from my development portfolio. A refreshed case study will document its features and implementation.']},
 {id:'wormhole',title:'WormHole',category:'experiment',kind:'Web 3D · Interactive space',year:'2020',image:'wormhole.webp',description:'A small world inside your browser.',body:'An explorable virtual space built with Three.js and Blender.',role:'3D design · Web development',stack:'Three.js · Blender',link:'https://github.com/hreisis/threeExhibit',linkLabel:'View source code',details:['An experiment connecting spatial design and browser-based interaction.']},
 {id:'after',title:'After Image',category:'experiment',kind:'Artificial intelligence · Visual study',year:'2019–2021',image:'after-image.webp',description:'Experiments in machine perception.',body:'An AI-related visual experiment from my earlier digital portfolio.',role:'Creative research · Visual experimentation',gallery:['after-image.webp'],details:['Project description, method, and credits are being prepared.']},
 {id:'mojave',title:'Mojave',category:'experiment',kind:'AI · Programming · Urban',year:'2019–2021',image:'mojave.webp',description:'An experiment across digital disciplines.',body:'A cross-disciplinary project bringing together artificial intelligence, programming, games, and urban questions.',role:'Creative technology · Spatial research',gallery:['mojave.webp'],details:['Project description, method, and credits are being prepared.']},
 {id:'pirates',title:'Pirates',category:'product',kind:'Mobile application · Music',year:'2023',image:'pirates.webp',description:'Connecting musicians and rehearsal spaces.',body:'A mobile application for livehouses to publish promotions and for musicians to reserve studios and receive local notifications.',role:'Application development · Interface design',link:'https://github.com/hreisis/pirates',linkLabel:'View source code',details:['An earlier mobile development project. Feature walkthrough and technical notes to follow.']},
 {id:'paradiso',title:'Paradiso',category:'product',kind:'Web application · Community',year:'2023',image:'paradiso.webp',description:'A place for boba lovers.',body:'A community website where customers can post comments and save their favorite places.',role:'Full-stack development · Interface design',link:'https://github.com/hreisis/paradiso-aws',linkLabel:'View source code',details:['An earlier full-stack development project. A refreshed case study will follow.']},
 {id:'super-hongo',title:'Super Hongo',category:'space',kind:'Environment design · Spatial study',year:'2019–2021',image:'hongo.webp',description:'An exploration of imagined environments.',body:'An environment-design project from my earlier digital portfolio, exploring speculative spaces through digital form.',role:'Environment design · Spatial exploration',gallery:['hongo.webp'],details:['Selected imagery from the original digital portfolio.','The exact project year, process, and credits will be added with the full case study.']},
 {id:'slice-it',title:'Slice It!',category:'experiment',kind:'Robotics · Parametric design',year:'2019',image:'slice-it.webp',description:'From parametric geometry to a physical installation.'}
];
